# Generated by Django 5.2.3 on 2025-06-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
                ('punzonado_width_lenght', models.IntegerField()),
                ('punzonado_height_lenght', models.IntegerField()),
                ('tejido_width_lenght', models.IntegerField()),
                ('tejido_height_lenght', models.IntegerField()),
                ('micrado_width_lenght', models.IntegerField()),
                ('micrado_height_lenght', models.IntegerField()),
            ],
        ),
    ]
