# Generated by Django 5.2.3 on 2025-06-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_confeccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confeccion',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
